### ISSUE TITLE
Login tab slightly bigger than the skin 

### ISSUE THREAD

**Issue by PNDA425** [DirtDiglett/Pressure2#107]
#### Are you using Pressure2 or Pressure2 Dark?
Pressure 2 Dark

#### Description of the issue.
On the login screen, the window has a bigger resolution than the skin, it results in a grey bar at the right.

#### Does it also occur on Steam without the skin installed?
No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
No, yes

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10

#### Are you using the latest stable release or using the latest commit version?
Lastest stable release

#### A screenshot of the issue.
http://imgur.com/MbFrnzo

#### Steps to reproduce the issue.
Launch steam with the skin active.

**Comment by fps40** [comment]
因为你的桌面分辨率太高了，超过了他的素材。

**Comment by FlamingFox911** [comment]
What fps40 said might be right. Because the skin uses images as a background, if the images are too small to support the resolution size what will happen is the image will not be able to cover all the image (as seen in your screenshot). Unless there was a way to stretch the image to cover the entire login page, there isn't much that can be done except get a new image.

**Comment by DoctorDinosaur** [comment]
Kinda Fixed in my unofficial patch: https://github.com/CptDinosaur/Pressure2DarkPatch  I nudged it over a little

**Comment by DirtDiglett** [comment]
Fixed for 1.1 Release
