### ISSUE TITLE
Steam has a new interface update. Please make this skin compatible with the new steam interface.

### ISSUE THREAD

**Issue by ydzccd** [DirtDiglett/Pressure2#124]

**Comment by leyyce** [comment]
I'm currently working on a quick and dirty fix that I will upload later this evening in the steam group. It's not perfect because I had no experience with steam skinning but it looks OK and works 

Edit: You can get the fix [here](https://steamcommunity.com/groups/pressureskin/discussions/0/3051633726576849955/)
