### ISSUE TITLE
Issues with last development commits

### ISSUE THREAD

**Issue by BanCrash** [DirtDiglett/Pressure2#128]
Hello! I just download the last commit of dev and found some (little) issues (and one I don't know if it's an issue or a feature). I'm using the dark version.

Overlapping texts in spanish:
Settings -> Account -> Security State
![image](https://user-images.githubusercontent.com/11770760/44202470-5b879a00-a14c-11e8-97ec-9e6adb37c952.png)

(Administrar la protección de la c... instead "Administrar la protección de la cuenta")

Settings -> On the game -> Keycup for screenshot
![image](https://user-images.githubusercontent.com/11770760/44202517-7d811c80-a14c-11e8-84f1-6c655781ae0c.png)

(Carpeta de capturas de... instead "carpeta de capturas de pantalla").

Settings -> Retransmision
![image](https://user-images.githubusercontent.com/11770760/44202561-a1dcf900-a14c-11e8-810c-b7ca458cd21e.png)

(Configuración Avanzad... instead "Configuación avanzada". (2 times)
Establecer codigo pin p... instead "Establecer codigo pin para steam link".)

Settings -> Music -> Database
![image](https://user-images.githubusercontent.com/11770760/44202423-37c45400-a14c-11e8-9dd9-f1ef7b8f022c.png)

"escaner carpetas (...)" not are showed very well.

Settings -> Preload ¿shadow?

![image](https://user-images.githubusercontent.com/11770760/44202689-f6807400-a14c-11e8-8757-6aceebdc1f25.png)

(Precargar sombreador...) Has points but don't know what follows.

This is on the left panel of the settings, I mean:

![image](https://user-images.githubusercontent.com/11770760/44202713-05ffbd00-a14d-11e8-95e4-a92bd4883d4a.png)

And this was different in the last release of dark pressure, so I don't know it's a feature or an issue:

Actual:
![image](https://user-images.githubusercontent.com/11770760/44202769-262f7c00-a14d-11e8-96e2-26718913e53f.png)

Last release of dark pressure:

![image](https://user-images.githubusercontent.com/11770760/44202809-44957780-a14d-11e8-9f1d-26d9dc46ddd5.png)

So before was grey, and now it's white. It's on the detail view of games.

In any case thanks for fixing all bugs and update this awesome skin!!

**Comment by DirtDiglett** [comment]
Wow that was fast!

I've fixed all but one of the things you mentioned here. I can't fix the "Carpeta de capturas de..." because I just do not have the spare space on the side of that area to do it. The rest is fixed though.

The last bit about the white section - that's not a bug, I've done a lot of internal changes to get Dark and Light as one theme, there's just a new way to apply dark mode that I will explain when I do the announcement for Pressure 1.1 release (Basically, copy+paste all the stuff in the "+ DARK MODE" folder into the main folder, overwrite. Then enable the mode in the "theme.ini" file).

**Comment by BanCrash** [comment]
Perfect, thanks you!!

That was fast too! ;)

Ah, I thought the only thing was to change the setting on theme.ini. Well enough, thanks!
