### ISSUE TITLE
[Friends List] Weird red line near search bar, goes away when search box is clicked on

### ISSUE THREAD

**Issue by jessb321** [DirtDiglett/Pressure2#17]
With [this](https://github.com/DirtDiglett/Pressure2/commit/367764f02bba3a59c2545c37ea05c274330d0bdc) commit, this happens on the friends list.
<img width="253" alt="screen shot 2016-02-25 at 2 26 52 pm" src="https://cloud.githubusercontent.com/assets/9222609/13308942/4279830e-dbcc-11e5-8bc4-f06ddf31c5bc.png">

It disappears when you click on the search box though.
I have now tested on windows and its happening there as well as on OS X

**Comment by Js41637** [comment]
Yeah the commit is titled 'Testing Friends Dialog', easiest way to see where things are is to make them a color that stands out.

**Comment by jessb321** [comment]
Ah, so not a bug then?

**Comment by DirtDiglett** [comment]
No, not a bug. I am going to be putting a lot of random things in the coming commits while I fix the various bugs reported in the 1.0 release.

Please stick to using the stable version provided in the official release, otherwise this sort of thing will keep happening while you sit on the bleeding edge.
