### ISSUE TITLE
Friends List, Avatar Settings

### ISSUE THREAD

**Issue by Kobi-Blade** [DirtDiglett/Pressure2#43]
#### Description of the issue.

Pressure² doesn't resize the Window leaving an awful blank space when we disable Avatars on Friends List.
#### Does it also occur on Steam without the skin installed?

No.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

No.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10.
#### Are you using the latest stable release or using the latest commit version?

Latest stable release (1.0.1).
#### A screenshot of the issue.

http://imgur.com/0WX422b
#### Steps to reproduce the issue.

Disable Avatars on Friends List.

**Comment by Asphira** [comment]
Oh.. this again, I remember when we had to fix this on pressure 1, I may look into it for Dirt seeing as I helped fix that on p1

**Comment by Asphira** [comment]
Actually at least that is not as bad as last time, should be quickly fixable

**Comment by Asphira** [comment]
Hmm not 100% sure if that one is fixable, should be though

**Comment by Asphira** [comment]
Only two real options for this, leave where is, or have it showing near the top of the bottom area instead, both will look out of place regardless as FriendPanelSelf itself can not have it's layout changed but instead just borrows the layout from FriendPanel_compact.layout and dodgy insetting fixes will not work in this case as the clickable region would still be top or bottom respectively depending on where chosen to be placed as its base

**Comment by Asphira** [comment]
Scratch all of the above, due to what causes the FriendsList Performance issue which has been fixed in a prior issue, where it currently sits in nonavatar view is the only option, sorry. (spent about 2 hours playing around with it to try and change positioning including having it show correctly in avatar view with it showing near the top of the bottom section in non avatar view but got the old 35% performance issue even after multiple attempts to fix the performance)

Dirt close when you want to as not fixable from my understanding since the only reason it resizes in pressure is because everything else follows the placement of the SelfPanel but being at the bottom I can not seem to make the friends list section itself end before it which would allow us to replicate that effect
