### ISSUE TITLE
Last category banner not completely visible if category collapsed

### ISSUE THREAD

**Issue by benutzer193** [DirtDiglett/Pressure2#54]
#### Description of the issue.

If the last category is collapsed, you can't see the complete banner or text when completely scrolled down.
Does not happen, if the category is expanded (Last game name is completely visible).

This is really **low** priority, but I just wanted to report.
#### Does it also occur on Steam without the skin installed?

No.
#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

Yes, yes.
#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Arch Linux.
#### Are you using the latest stable release or using the latest commit version?

Latest commit (dev and master).
#### A screenshot of the issue.

![screenshot](https://cloud.githubusercontent.com/assets/9975220/15994271/ef8da0b0-30ff-11e6-9a94-5f494c5c897f.jpg)
#### Steps to reproduce the issue.

Collapse last category.
Scroll down completely.

**Comment by nuggs** [comment]
It happens for me on both Windows 10 and Arch Linux as well.

**Comment by DirtDiglett** [comment]
It's something that I have never been able to resolve, the space that is cut off is due to Steam assuming the category header is the same height as in default, and thus adjusts the height accordingly and cutting it off. I don't think there's a way for this to be fixed. Other skins got around it by just using the same height for the headings as default, but alas I am not happy with that workaround.
