### ISSUE TITLE
not usable in 1366*768

### ISSUE THREAD

**Issue by nedelko1maks** [DirtDiglett/Pressure2#6]
http://s017.radikal.ru/i404/1602/7b/b43077bb67ce.png

**Comment by Js41637** [comment]
I'm sorry i'm not quite following from the picture. What appears to be the issue? Is text not fitting?

**Comment by nedelko1maks** [comment]
![35](https://cloud.githubusercontent.com/assets/17452466/13285947/c0fdbc52-db06-11e5-9250-1c9fd907401f.png)

**Comment by Js41637** [comment]
That's actually how the skin is _meant_ to look. The tiny indent at the top i'm not sure about, I have it as well. The second one, it is meant to be indented relative to the game image (like it is on the right side) it probably just looks a bit weird because you don't have a scrollbar there.
![image](https://cloud.githubusercontent.com/assets/6258213/13286001/971def64-db52-11e5-9d28-5320a1ab928c.png)

**Comment by DirtDiglett** [comment]
Hi @nedelko1maks, thanks for your report.

In the image you've provided, the top red circle shows a slight misalignment by a few pixels, which is an aesthetic issue I will sort out as a low-priority bug.

The second circle though, it is not showing anything unexpected? Can you perhaps elaborate on what the issue is there?
