### ISSUE TITLE
Too much white :(

### ISSUE THREAD

**Issue by Zer0Mood** [DirtDiglett/Pressure2#63]
Nothing technically wrong with it, but I'd love to see some color added to the library. It's just way too dull and bright white for me. BUT I do love the rest of it!! I just can't get over all the white.

**Comment by FlamingFox911** [comment]
That was the way it was supposed to be designed. There has been an [ongoing discussion](https://github.com/DirtDiglett/Pressure2/issues/42) about this, mainly regarding the brightness and colour scheme as well as a possibility of dark/classic theme. An unofficial Dark Theme (dubbed [Pressure2Dark](https://github.com/screwyluie/Pressure2/tree/Pressure2Dark)) has been made in the meantime, albeit a bit out of date due to recent additions to Steam options.
