### ISSUE TITLE
Dark version

### ISSUE THREAD

**Issue by Xseba360** [DirtDiglett/Pressure2#7]
Hello. Are there any plans for a dark background version instead of the white one? :smile:

**Comment by OrI3iT** [comment]
I second this! I love the theme, but it's way to bright.

**Comment by Hatomike** [comment]
I would love too a dark tweak of this theme !

**Comment by Anidion** [comment]
Please make this an option, as I personally love the white skin and I'm sure there are others who also do.

**Comment by johnmcdee** [comment]
Great work!
I would love an option for a dark version too

**Comment by jessb321** [comment]
I could really use this, my eyes being as sensitive as they are

**Comment by DirtDiglett** [comment]
Taken from the announcement I posted today:

> 170+ comments, reddit messages, and steam messages... I get it, you want a dark theme, you don't like the light theme. 
> 
> I never intended Pressure² to be anything but what it is now, and I'm not promising a dark theme for it nor am I taking that option off the table, I need to think on it further. What I will promise is that "Pressure Classic" is going to begin development now, and it will be dark, it will be a good blend of Pressure1 and Pressure² - and this one is for you guys, I personally won't ever use it, but I'm going to do it for you. Pressure Classic will be a dark theme.

Out of curiosity, @willyb321 what do you do for the 90% of light-themed/white websites and applications?

**Comment by Hatomike** [comment]
@DirtDiglett ,Just so that you can see it.
Don't change the theme from light to dark, it should be what you want it to be.
If you can, add some tweak in config.ini for this option.

**Comment by jessb321** [comment]
@DirtDiglett I use extensions such as [this](https://chrome.google.com/webstore/detail/care-your-eyes/fidmpnedniahpnkeomejhnepmbdamlhl?hl=en) to change the background colour for websites that are particularly bad on my eyes. Also, perhaps a config option to change the colour of whitespace? I personally haven't developed skins much, mainly because I'm terrible at design, but that seems like something that can happen? I believe that air or metro skin had something like that but I'm not sure myself. Thanks for listening though, its a rare thing these days sadly.

**Comment by skittoh** [comment]
I also used to dislike this light skin, but I sticked with it and now I'm enjoying it so far. Though still think a light grey would look better than white.
