### ISSUE TITLE
Pressure Dark 1.0.0. - Move Install Folder Option Placement Issue

### ISSUE THREAD

**Issue by RadioactiveLobster** [DirtDiglett/Pressure2#76]
#### Description of the issue.
The "Move Install Folder" option in the properties of a game is not in the correct place.

#### Does it also occur on Steam without the skin installed?
No

#### Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?
Yes. Issue also present when not opted into BETA.

#### What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)
Windows 10 Pro 64bit

#### Are you using the latest stable release or using the latest commit version?
Latest Stable of Pressure Dark 1.0.0

#### A screenshot of the issue.
[Here](http://i.imgur.com/b6y5uBC.png)

#### Steps to reproduce the issue.
Right click any installed game in Library, click "Properties", then "Local Files", look for the "Move Install Folder" Option.

**Comment by FlamingFox911** [comment]
Formatting Error. Usually happens when new features are added.

I believe the fix has been implemented into the Light Version of Pressure<sup>2</sup>, but hasn't been ported to Dark **_yet_**. EDIT: See a6290507dc94d920d7c24aa5e4639cb24a4c94a6 in the Development Branch of Pressure<sup>2</sup>.

The file in question is steam\cached\gameproperties_localfiles.res

**Comment by Dave247** [comment]
I fixed it myself here cae2c4da8b3aecc5588cd8b238faf35eb05fb9bc as by simply using the same file from the non dark version, as @FlamingFox911 himself said.

**Comment by Dave247** [comment]
This issue was moved to Dave247/Pressure2#5
